blank_issues_enabled: false
contact_links:
  - name: Schoology Plus Discord Server
    url: https://discord.schoologypl.us
    about: Please use our Discord server for feature requests, getting help, or just to chat with other members.
  - name: Schoology Plus Documentation
    url: https://schoologypl.us/docs
    about: IUse this help site to learn more about using What-If Grades and our Theme Editor
